WITH ALL_O AS((
	(SELECT PERSON_VISITS.PIZZERIA_ID
	 FROM PERSON_VISITS
	 JOIN PERSON ON PERSON.ID = PERSON_VISITS.PERSON_ID
	 WHERE PERSON.GENDER = 'male')
	EXCEPT ALL
	(SELECT PERSON_VISITS.PIZZERIA_ID
	 FROM PERSON_VISITS
	 JOIN PERSON ON PERSON.ID = PERSON_VISITS.PERSON_ID
	 WHERE PERSON.GENDER = 'female'))
			  UNION ALL (
				  (SELECT PERSON_VISITS.PIZZERIA_ID
				   FROM PERSON_VISITS
				   JOIN PERSON ON PERSON.ID = PERSON_VISITS.PERSON_ID
				   WHERE PERSON.GENDER = 'female')
				  EXCEPT ALL
				  (SELECT PERSON_VISITS.PIZZERIA_ID
				   FROM PERSON_VISITS
				   JOIN PERSON ON PERSON.ID = PERSON_VISITS.PERSON_ID
				   WHERE PERSON.GENDER = 'male')))
SELECT DISTINCT NAME AS PIZZERIA_NAME
FROM ALL_O
JOIN PIZZERIA ON PIZZERIA.ID = ALL_O.PIZZERIA_ID
ORDER BY NAME