CREATE INDEX IDX_PERSON_ORDER_MULTI ON PERSON_ORDER (PERSON_ID, MENU_ID, ORDER_DATE)
WHERE PERSON_ID = 8 AND MENU_ID = 19;
	
SET ENABLE_SEQSCAN = OFF;

EXPLAIN ANALYZE
SELECT PERSON_ID, MENU_ID, ORDER_DATE
FROM PERSON_ORDER
WHERE PERSON_ID = 8 AND MENU_ID = 19;