WITH NOT_ORDER AS
	(SELECT MENU.ID AS MENU_ID
	FROM MENU
	EXCEPT SELECT PERSON_ORDER.MENU_ID
	FROM PERSON_ORDER)
SELECT PIZZA_NAME, PRICE,
	PIZZERIA."name" AS PIZZERIA_NAME
FROM NOT_ORDER
JOIN MENU ON MENU.ID = MENU_ID
JOIN PIZZERIA ON PIZZERIA.ID = MENU.PIZZERIA_ID
ORDER BY PIZZA_NAME, PRICE