SELECT PERSON.NAME,
	MENU.PIZZA_NAME,
	MENU.PRICE,
	MENU.PRICE - (MENU.PRICE * PERSON_DISCOUNTS.DISCOUNT / 100) AS DISCOUNT_PRICE,
	PIZZERIA.NAME AS PIZZERIA_NAME
FROM PERSON_ORDER
JOIN PERSON ON PERSON.ID = PERSON_ORDER.PERSON_ID
JOIN MENU ON MENU.ID = PERSON_ORDER.MENU_ID
JOIN PIZZERIA ON PIZZERIA.ID = MENU.PIZZERIA_ID
LEFT JOIN PERSON_DISCOUNTS ON PERSON_DISCOUNTS.PERSON_ID = PERSON_ORDER.PERSON_ID
AND PERSON_DISCOUNTS.PIZZERIA_ID = MENU.PIZZERIA_ID
ORDER BY PERSON.NAME,
	MENU.PIZZA_NAME