WITH DATES AS
	(SELECT DAY::date AS MISSING_DATE
	FROM GENERATE_SERIES('2022-01-01'::date,'2022-01-10'::date,'1 day') AS DAY)
SELECT DATES.MISSING_DATE
FROM DATES
FULL JOIN
	(SELECT PERSON_VISITS.VISIT_DATE
	FROM PERSON_VISITS WHERE PERSON_ID = 1
	OR PERSON_ID = 2) AS VISITS ON MISSING_DATE = VISITS.VISIT_DATE
WHERE VISITS.VISIT_DATE IS NULL
ORDER BY VISITS.VISIT_DATE