INSERT INTO PERSON_VISITS
VALUES (
	(SELECT MAX(ID) AS ID
	 FROM PERSON_VISITS) + 1,
	(SELECT DISTINCT PERSON_ID
	 FROM PERSON_VISITS
	 JOIN PERSON ON PERSON.ID = PERSON_VISITS.PERSON_ID
	 WHERE PERSON.NAME = 'Dmitriy' ),
	(SELECT MIN(PIZZERIA.ID)
	 FROM PIZZERIA
	 JOIN MENU M ON M.PIZZERIA_ID = PIZZERIA.ID
	 AND M.PRICE < 800
	 AND PIZZERIA.NAME <> 'Papa Johns'), '2022-01-08'::date);
	 REFRESH MATERIALIZED VIEW MV_DMITRIY_VISITS_AND_EATS;