WITH NAMES AS
	(SELECT ID, NAME
	FROM PERSON
	WHERE GENDER = 'male'
	AND (ADDRESS = 'Moscow' OR ADDRESS = 'Samara'))
SELECT NAMES.NAME
FROM PERSON_ORDER
JOIN MENU ON MENU.ID = PERSON_ORDER.MENU_ID
JOIN NAMES ON NAMES.ID = PERSON_ORDER.PERSON_ID
WHERE PIZZA_NAME = 'pepperoni pizza'
	OR PIZZA_NAME = 'mushroom pizza'
ORDER BY NAMES.NAME DESC