SELECT PERSON_ORDER.ORDER_DATE,
	CONCAT(PERSON.NAME,
		' (age:', PERSON.AGE, ')') AS PERSON_INFORMATION
FROM PERSON_ORDER
JOIN PERSON ON PERSON.ID = PERSON_ORDER.PERSON_ID
ORDER BY PERSON_ORDER.ORDER_DATE, PERSON_INFORMATION