SELECT ORDER_DATE AS ACTION_DATE,
	(SELECT NAME FROM PERSON
		WHERE PERSON.ID = PERSON_ORDER.PERSON_ID ) AS PERSON_NAME
FROM PERSON_ORDER INTERSECT
SELECT VISIT_DATE AS ACTION_DATE,
	(SELECT NAME FROM PERSON
		WHERE PERSON.ID = PERSON_VISITS.PERSON_ID ) AS PERSON_NAME
FROM PERSON_VISITS
ORDER BY ACTION_DATE, PERSON_NAME DESC