INSERT INTO MENU
VALUES ((SELECT MAX(ID) + 1 AS ID FROM MENU),
		(SELECT DISTINCT PIZZERIA_ID 
		 FROM MENU 
		 JOIN PIZZERIA ON MENU.PIZZERIA_ID = PIZZERIA.ID 
		 WHERE PIZZERIA.NAME = 'Dominos'), 'sicilian pizza', 900)