INSERT INTO PERSON_ORDER
VALUES ((SELECT (MAX(PERSON_ORDER.ID) + 1) FROM PERSON_ORDER),
 (SELECT ID FROM PERSON WHERE NAME = 'Denis'),
 (SELECT MENU.ID FROM MENU WHERE PIZZA_NAME = 'sicilian pizza' ),
 ('2022-02-24'::date)),
 ((SELECT (MAX(PERSON_ORDER.ID) + 2) FROM PERSON_ORDER),
 (SELECT ID FROM PERSON WHERE NAME = 'Irina'),
 (SELECT MENU.ID FROM MENU WHERE PIZZA_NAME = 'sicilian pizza' ),
 ('2022-02-24'::date))