SELECT PERSON_ORDER.ORDER_DATE,
	CONCAT(PERSONS.NAME, ' (age:', PERSONS.AGE, ')') AS PERSON_INFORMATION
FROM PERSON_ORDER
NATURAL JOIN PERSON AS PERSONS(PERSON_ID, NAME, AGE, GENDER, ADDRESS)
ORDER BY PERSON_ORDER.ORDER_DATE, PERSON_INFORMATION