(SELECT PIZZERIA.NAME, COUNT(PERSON_ORDER.ID) AS COUNT, 'order' AS ACTION_TYPE
		FROM PIZZERIA
		JOIN MENU ON PIZZERIA.ID = MENU.PIZZERIA_ID
		JOIN PERSON_ORDER ON MENU.ID = PERSON_ORDER.MENU_ID
		GROUP BY PIZZERIA.NAME
		ORDER BY 2 DESC
		LIMIT 3)
UNION
(SELECT PIZZERIA.NAME, COUNT(PERSON_VISITS.ID) AS COUNT, 'visit' AS ACTION_TYPE
		FROM PIZZERIA
		JOIN PERSON_VISITS ON PIZZERIA.ID = PERSON_VISITS.PIZZERIA_ID
		GROUP BY PIZZERIA.NAME
		ORDER BY 2 DESC
		LIMIT 3)
ORDER BY 3, 2 DESC