CREATE VIEW V_PRICE_WITH_DISCOUNT AS
SELECT PERSON.NAME AS NAME,
	MENU.PIZZA_NAME,
	PRICE,
	ROUND (PRICE - (PRICE * 0.1)) AS DISCOUNT_PRICE
FROM PERSON_ORDER
JOIN PERSON ON PERSON.ID = PERSON_ORDER.PERSON_ID
JOIN MENU ON PERSON_ORDER.MENU_ID = MENU.ID
ORDER BY 1,2