SELECT MENU.PIZZA_NAME, MENU.PRICE,
	PIZZERIA.NAME AS PIZZERIA_NAME,
	PERSON_VISITS.VISIT_DATE
FROM MENU
JOIN PERSON_VISITS ON PERSON_VISITS.PIZZERIA_ID = MENU.PIZZERIA_ID
JOIN PERSON ON PERSON.ID = PERSON_VISITS.PERSON_ID
JOIN PIZZERIA ON PIZZERIA.ID = MENU.PIZZERIA_ID
WHERE PERSON.NAME = 'Kate' AND (PRICE >= 800 AND PRICE <= 1000)
ORDER BY PIZZA_NAME