CREATE UNIQUE INDEX IDX_PERSON_ORDER_ORDER_DATE ON PERSON_ORDER (PERSON_ID, MENU_ID)
WHERE ORDER_DATE = '2022-01-01'::date;

SET ENABLE_SEQSCAN = OFF;

EXPLAIN ANALYZE
SELECT PERSON_ID, MENU_ID
FROM PERSON_ORDER
WHERE ORDER_DATE = '2022-01-01'::date;