SELECT (CASE 
		WHEN PERSON.NAME IS NULL THEN '-'
		ELSE PERSON.NAME
		END) AS PERSON_NAME, VISIT_DATE,
		(CASE
		 WHEN PIZZERIA.NAME IS NULL THEN '-'
		 ELSE PIZZERIA.NAME
		END) AS PIZZERIA_NAME
FROM PERSON
FULL JOIN
	(SELECT *
	 FROM PERSON_VISITS
	 WHERE PERSON_VISITS.VISIT_DATE = '2022-01-01'::date
	 OR PERSON_VISITS.VISIT_DATE = '2022-01-02'::date
	 OR PERSON_VISITS.VISIT_DATE = '2022-01-03'::date) AS DATES ON PERSON.ID = DATES.PERSON_ID
FULL JOIN PIZZERIA ON DATES.PIZZERIA_ID = PIZZERIA.ID
ORDER BY PERSON_NAME, VISIT_DATE, PIZZERIA_NAME