SELECT PIZZERIA.NAME AS PIZZERIA_NAME
FROM PERSON_VISITS
JOIN PIZZERIA ON PIZZERIA.ID = PIZZERIA_ID
JOIN PERSON ON PERSON.ID = PERSON_ID
JOIN MENU ON PIZZERIA.ID = MENU.PIZZERIA_ID
WHERE VISIT_DATE = '2022-01-08'::date
	AND PERSON.NAME = 'Dmitriy'
	AND PRICE < 800