SELECT ADDRESS, PIZZERIA.NAME, COUNT(PERSON_ORDER.ID) AS COUNT_OF_ORDERS
FROM PERSON_ORDER
JOIN PERSON ON PERSON.ID = PERSON_ORDER.PERSON_ID
JOIN MENU ON MENU.ID = PERSON_ORDER.MENU_ID
JOIN PIZZERIA ON PIZZERIA.ID = MENU.PIZZERIA_ID
GROUP BY ADDRESS, PIZZERIA.NAME
ORDER BY 1, 2