INSERT INTO PERSON_ORDER (ID, PERSON_ID, MENU_ID, ORDER_DATE)
SELECT (GENERATE_SERIES
		(((SELECT MAX(ID) + 1 FROM PERSON_ORDER)),
		 ((SELECT MAX(ID) FROM PERSON_ORDER) +
		  (SELECT COUNT(*) FROM PERSON)))),
		  (GENERATE_SERIES (
			  (SELECT MIN(ID) FROM PERSON),
			  (SELECT COUNT(*) FROM PERSON))),
			  (SELECT MENU.ID FROM MENU
			   WHERE MENU.PIZZA_NAME = 'greek pizza'), ('2022-02-25'::date)