SELECT PIZZA_NAME, PIZZERIA.NAME AS PIZZERIA_NAME, PRICE
FROM MENU
FULL JOIN PIZZERIA ON PIZZERIA.ID = PIZZERIA_ID
WHERE PIZZA_NAME = 'pepperoni pizza' OR PIZZA_NAME = 'mushroom pizza'
ORDER BY PIZZA_NAME, PIZZERIA.NAME