CREATE SEQUENCE SEQ_PERSON_DISCOUNTS
START 1;
ALTER TABLE PERSON_DISCOUNTS
ALTER COLUMN ID
SET DEFAULT NEXTVAL ('seq_person_discounts');
SELECT SETVAL('seq_person_discounts',
			  (SELECT COUNT(PERSON_DISCOUNTS.ID)
			   FROM PERSON_DISCOUNTS) + 1);