WITH FAM AS
	(SELECT DISTINCT PIZZERIA_ID
		FROM PERSON_ORDER
		JOIN PERSON ON PERSON.ID = PERSON_ORDER.PERSON_ID
		JOIN MENU ON MENU.ID = PERSON_ORDER.MENU_ID
		WHERE PERSON.GENDER = 'female' ),
	MEN AS
	(SELECT DISTINCT PIZZERIA_ID
		FROM PERSON_ORDER
		JOIN PERSON ON PERSON.ID = PERSON_ORDER.PERSON_ID
		JOIN MENU ON MENU.ID = PERSON_ORDER.MENU_ID
		WHERE PERSON.GENDER = 'male' ),
	ONLY_ONE AS (
		(SELECT * FROM FAM
		 EXCEPT
		 SELECT * FROM MEN)
		UNION
		(SELECT * FROM MEN
		 EXCEPT
		 SELECT * FROM FAM))
SELECT PIZZERIA.NAME AS PIZZERIA_NAME
FROM ONLY_ONE
JOIN PIZZERIA ON PIZZERIA.ID = ONLY_ONE.PIZZERIA_ID
ORDER BY PIZZERIA.NAME