WITH WOMEN_ORDER AS
	(SELECT PERSON.ID, NAME, MENU.PIZZA_NAME
	FROM PERSON
	JOIN PERSON_ORDER ON PERSON_ORDER.PERSON_ID = PERSON.ID
	JOIN MENU ON MENU.ID = PERSON_ORDER.MENU_ID
	WHERE GENDER = 'female' )
SELECT NAME
FROM WOMEN_ORDER
WHERE PIZZA_NAME = 'cheese pizza' INTERSECT
	SELECT NAME
	FROM WOMEN_ORDER WHERE PIZZA_NAME = 'pepperoni pizza'
ORDER BY NAME