WITH AMOUNT AS
	(SELECT PERSON_ORDER.PERSON_ID,
			MENU.PIZZERIA_ID,
			COUNT(PERSON_ORDER.PERSON_ID)
		FROM PERSON_ORDER
		JOIN MENU ON PERSON_ORDER.MENU_ID = MENU.ID
		GROUP BY PERSON_ID,
			MENU.PIZZERIA_ID)
INSERT INTO PERSON_DISCOUNTS (ID,PERSON_ID, PIZZERIA_ID, DISCOUNT)
SELECT ROW_NUMBER() OVER () AS ID,
	AMOUNT.PERSON_ID,
	AMOUNT.PIZZERIA_ID,
	(CASE
	 WHEN AMOUNT.COUNT = 1 THEN 10.5
	 WHEN AMOUNT.COUNT = 2 THEN 22
	 ELSE 30
	 END) AS DISCOUNT
FROM AMOUNT