CREATE TABLE PERSON_DISCOUNTS (ID bigint PRIMARY KEY,
PERSON_ID bigint NOT NULL,
PIZZERIA_ID bigint NOT NULL,
DISCOUNT numeric, CONSTRAINT FK_PERSON_DISCOUNTS_PERSON_ID
FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID),
CONSTRAINT FK_PERSON_DISCOUNTS_PIZZERIA_ID
FOREIGN KEY (PIZZERIA_ID) REFERENCES PIZZERIA(ID));