CREATE VIEW V_SYMMETRIC_UNION AS WITH R_SUR_S AS (
	(SELECT PERSON_ID
	 FROM PERSON_VISITS
	 WHERE VISIT_DATE = '2022-01-02'::date
	 EXCEPT SELECT PERSON_ID
	 FROM PERSON_VISITS
	 WHERE VISIT_DATE = '2022-01-06'::date)
	UNION
	(SELECT PERSON_ID
	 FROM PERSON_VISITS
	 WHERE VISIT_DATE = '2022-01-06'::date
	 EXCEPT SELECT PERSON_ID
	 FROM PERSON_VISITS
	 WHERE VISIT_DATE = '2022-01-02'::date ))
SELECT *
FROM R_SUR_S
ORDER BY 1